language: java
jdk:
- oraclejdk8

script:
- mvn test

branches:
  only:
  - master

 deploy:
   provider: cloudfoundry
   username: ragrawal@solstice.com
   password: "OeeFo4PEsXNmZb4E92+m5zf8xAsdjAJtb8ClfUDTPF5WpFE7Ni5+90+Sen3kOIlZbWlWwfZdiF4IEZRx/5/1YyoW5GLdEWV5cpz2HJc++Yi46AfK2KXta6z9pELOROMNFavkAvoZVbQgK97nQc9+IQgjup9K8BxweIDL9Toy9zbBqR72WcOk+UEDMJd7DzQgnrSwAaIEiyk6fPmH9NlFyhmrXCHx1axwSJ5uXY90wNppTLQQgaxyl8/2TMfkQhNgxuBARePdWleshgXwT/DgrgIxNtdzy5CS25AiUOpF6h7l5ySAK7wYUmE3y3/adnp5dF5Np2u9ePiGVM4VgHzmfrHbWnp8Kx/7MI33kXLLcoXimAswtMzSJXSUbAVG6/qiqBkQRbojSKRyNsLt0Jz80ZqwTp8nli4OIBgnERx3YpApYzgULX5w+PP0HtvTeXKszv8NVTE2fLyxcjcw8s8UcHuPFxRJrEDZwwUTC3T/7O8pnM8OCR0OE6oJ6hf9A6LNGXkh/aOkB/s/tdKwd3ZoyvZMcfR2jaubytJWj2l8ZuCWvjZGZOQ7/qVCSE/Vu3N0ASyjkuYmMKrrCweJ9q7520ITDKga6tjHYBESpzSBh20F72aBTOc7op8BYS1/tA82vTHp7t1YjgMZ6K0WdqD6eaRMH4HvCvNJjInfV96tqnw="
   api: https://api.run.pivotal.io
   organization: solstice-org
   space: ritu-cnt